name: Robot Framework Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone do projeto
        uses: actions/checkout@v4

      - name: Configuração do Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalação das dependências
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-requests

      - name: Rodando os testes
        run: |
          robot --name "API Tests" --outputdir results/ tests/

      - name: Salvando os resultados dos testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: resultado-testes
          path: results/

  deploy:
    name: Configurar site
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://iza975.github.io/Testes_Frontend_Robot/report.html

    steps:
      - name: Configurando GitHub Pages
        uses: actions/configure-pages@v2

      - name: Baixando artefatos
        uses: actions/download-artifact@v4
        with:
          name: resultado-testes
          path: results/

      - name: Publicando artefatos no Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: results/

      - name: Deploy para o GitHub Pages
        uses: actions/deploy-pages@v1
